### ISSUE TITLE
Libraries not found & InvalidVersionSpec: Invalid version '~0.4.16]': invalid operator

### ISSUE THREAD

**Issue by Ganishk** [SAMashiyane/Naloxone#1]
I think the `requirements.txt` has been mixed with python-pip format for some libraries which is not working when we do `conda install --yes --file requirements.txt`.

**Original values (not working)**
```
category-encoders>=2.4.0
atplotlib<3.8.0 
kaleido>=0.2.1
ray[tune]>=1.0.0
evidently~=0.4.16]
```

Following are the changes I made, if these were not the expected ones, then kindly update the _requirements.txt_ or _README.md_ file.

**Modified values**
```
category_encoders>=2.4.0
matplotlib<3.8.0 
python-kaleido>=0.2.1
ray-tune>=1.0.0
evidently==0.4.16
```

**Comment by SAMashiyane** [comment]
Thank you, these items have been corrected.
